# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/60 * * * *'  # every 60 minutes

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: "bash -l {0}"
        run: |
          conda create -n 39 python==3.9
          conda activate 39
          pip install -r requirements.lock
          python app.py static
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        # Only deploy cronjob from main branch & repo
        if: success() && github.ref == 'refs/heads/main' && github.repository_owner == 'openteamsinc'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

